sudo: true

cache:
  directories:
    - "$HOME/.composer/cache/files"

language: php

matrix:
  fast_finish: true

#env:
#  global:
#    - PATH=${TRAVIS_BUILD_DIR}/travis/bin/:${PATH}

#services:
#  - docker

stages:
  - name: test
    if: type = pull_request
#  - name: build
#    if: type != pull_request AND branch = master

jobs:
  include:
    - stage: test
      name: test
      script:
        - make \
          install \
          test \
          deptrac \
          cs
