services:
  _defaults:
    autowire: false
    public: false

  app.dotenv:
    class: Symfony\Component\Dotenv\Dotenv

  app.dotenv_driver:
    class: Pararius\EnvChecker\Infrastructure\Specification\Dotenv\RealDotenvDriver
    arguments:
      - '@app.dotenv'

  app.finder:
    class: Symfony\Component\Finder\Finder

  app.specification_loader.dotenv:
    class: Pararius\EnvChecker\Infrastructure\Specification\Dotenv\Loader
    arguments:
      - '@app.dotenv_driver'

  app.implementation_loader.kubernetes:
    class: Pararius\EnvChecker\Infrastructure\Implementation\Kubernetes\Loader
    arguments:
      - '@app.finder'

  app.presentation.cli.console_command.check:
    public: true
    class: Pararius\EnvChecker\Presentation\Cli\Console\Command\CheckCommand
    arguments:
      - '@app.specification_loader.dotenv'
      - '@app.implementation_loader.kubernetes'

  app.presentation.cli.console_command.self_update:
    public: true
    class: Pararius\EnvChecker\Presentation\Cli\Console\Command\SelfUpdateCommand
    arguments:
      - '@humbug.self_update.updater'

  humbug.self_update.github_strategy:
    class: Humbug\SelfUpdate\Strategy\GithubStrategy
    calls:
      - ['setPackageName', ['pararius/env-checker']]
      - ['setPharName', ['env-checker.phar']]
      - ['setCurrentLocalVersion', ['%env(APP_VERSION)%']]

  humbug.self_update.updater:
    class: Humbug\SelfUpdate\Updater
    arguments:
      - 'bin/env-checker.phar'
      - false
    calls:
      - ['setStrategyObject', ['@humbug.self_update.github_strategy']]
