---
apiVersion: apps/v1
kind: Deployment
metadata: {}
spec:
  replicas: 2
  selector: {}
  template:
    metadata: {}
    spec:
      initContainers:
        - name: my-init-service
          image: my-init-service-image
          command: ["bin/my-tool", "command"]
          env:
            - name: DEFINED_IN_BOTH_1
              value: "..."
      containers:
        - name: my-service
          image: my-service-image
          command: ["bin/my-tool", "command"]
          env:
            - name: DEFINED_IN_BOTH_2
              value: "..."
